all:
	(cd misc; make all)
	(cd pipe; make all)
	(cd seq; make all)
	(cd y86-code; make all)

gui:
	(cd misc; make gui)
	(cd pipe; make gui)
	(cd seq; make gui)

clean:
	(cd pipe; make clean)
	(cd ptest; make clean)
	(cd seq; make clean)
	(cd misc; make clean)
	(cd y86-code; make clean)
	rm -f *.o *~

