all:	label button list text menu

clean: rm -r -f label button list text menu

label:	label.c
	cc -o label label.c -lX11 -lXaw

button:	button.c
	cc -o button button.c -lX11 -lXaw

list:	list.c
	cc -o list list.c -lX11 -lXaw

text:	text.c
	cc -o text text.c -lX11 -lXaw

menu:	menu.c
	cc -o menu menu.c -lX11 -lXaw

